### model
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
trust_remote_code: true

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all
pref_beta: 0.1
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]
use_unsloth: true
use_unsloth_gc: true

### dataset
dataset: resist_50
template: llama3
cutoff_len: 2048
# max_samples: 50000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: output/Llama-3.1-8B-Instruct_resist_50
logging_steps: 0.05
# save_steps: 500
save_strategy: epoch
max_new_tokens: 2048
plot_loss: true
overwrite_output_dir: true
push_to_hub: true
export_hub_model_id: Incomple/Llama-3.1-8B-Instruct_resist_50

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 1.0e-6
num_train_epochs: 1.0
lr_scheduler_type: linear
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
